#!/bin/sh

set -e

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
CONFIG_DIR="${SCRIPT_DIR}/Configurations"
MARLIN_DIR="${SCRIPT_DIR}/Marlin"
if [ "${GITHUB_ACTIONS}" = "true" ]; then
    ARTIFACTS_DIR="${SCRIPT_DIR}/.artifacts"
fi

# All Marlin Python scripts are python3-compatible, but most have a
# "python" shebang.  For python3-only envs, set up a workaround.
if ! command -v python >/dev/null; then
    TMPBIN="$(mktemp -d)"
    ln -sf "$(command -v python3)" "${TMPBIN}/python"
    export PATH="${TMPBIN}:${PATH}"
fi

ENVIRONMENT="${1}"
[ -n "${ENVIRONMENT}" ]
NOW="$(date '+%Y-%m-%d %H:%M:%S')"
NOWSHORT="$(date -d "${NOW}" '+%Y%m%d-%H%M%S')"

CONFIG_BRANCH="$(git -C "${CONFIG_DIR}" rev-parse --abbrev-ref HEAD)"
CONFIG_BRANCH_REV="$(git -C "${CONFIG_DIR}" log --format="%h" -n 1 HEAD)"
CONFIG_BRANCH_DATE="$(git -C "${CONFIG_DIR}" show -s --format=%ci HEAD | perl -ne '/^(\d{4})-(\d{2})-(\d{2})/ && print $1 . $2 . $3')"

MARLIN_BRANCH="$(git -C "${MARLIN_DIR}" rev-parse --abbrev-ref HEAD)"
MARLIN_BRANCH_REV="$(git -C "${MARLIN_DIR}" log --format="%h" -n 1 HEAD)"
MARLIN_BRANCH_DATE="$(git -C "${MARLIN_DIR}" show -s --format=%ci HEAD | perl -ne '/^(\d{4})-(\d{2})-(\d{2})/ && print $1 . $2 . $3')"

SCRIPT_BRANCH="$(git -C "${SCRIPT_DIR}" rev-parse --abbrev-ref HEAD)"
SCRIPT_BRANCH_REV="$(git -C "${SCRIPT_DIR}" log --format="%h" -n 1 HEAD)"
SCRIPT_BRANCH_DATE="$(git -C "${SCRIPT_DIR}" show -s --format=%ci HEAD | perl -ne '/^(\d{4})-(\d{2})-(\d{2})/ && print $1 . $2 . $3')"

git -C "${MARLIN_DIR}" checkout -- \
    platformio.ini \
    Marlin/Configuration.h \
    Marlin/Configuration_adv.h
cat <<"EOM" >> "${MARLIN_DIR}/platformio.ini"

[env:e3v2]
extends = env:STM32F103RE_creality
build_flags = ${env:STM32F103RE_creality.build_flags} -DCUSTOM_VERSION_FILE=_Version.h

[env:wdi3p]
extends = env:mega2560
build_flags = ${env:mega2560.build_flags} -DCUSTOM_VERSION_FILE=_Version.h
extra_scripts = ${env:mega2560.extra_scripts}
  pre:buildroot/share/PlatformIO/scripts/random-bin.py
EOM

cd "${MARLIN_DIR}"
PATH="${PATH}:${MARLIN_DIR}/buildroot/bin"

if [ "${ENVIRONMENT}" = "e3v2" ]; then
    cp \
        "${CONFIG_DIR}/config/examples/Creality/Ender-3 V2/CrealityV422/MarlinUI/Configuration.h" \
        "${MARLIN_DIR}/Marlin/"
    if [ -e "${CONFIG_DIR}/config/examples/Creality/Ender-3 V2/CrealityV422/MarlinUI/Configuration_adv.h" ]; then
        cp \
            "${CONFIG_DIR}/config/examples/Creality/Ender-3 V2/CrealityV422/MarlinUI/Configuration_adv.h" \
            "${MARLIN_DIR}/Marlin/"
    fi

    opt_set STRING_CONFIG_H_AUTHOR '"(rfinnie)"'
    opt_enable PID_EDIT_MENU
    opt_enable PID_AUTOTUNE_MENU
    opt_set DEFAULT_MAX_FEEDRATE '{ 500, 500, 12, 25 }'
    opt_disable PROBE_MANUALLY
    opt_enable BLTOUCH
    opt_set NOZZLE_TO_PROBE_OFFSET '{ -42, -10, -2.00 }'
    opt_set XY_PROBE_FEEDRATE '(120*60)'
    opt_set Z_PROBE_FEEDRATE_FAST '(12*60)'
    opt_set MULTIPLE_PROBING 2
    opt_set Z_CLEARANCE_DEPLOY_PROBE 5
    opt_set Z_CLEARANCE_BETWEEN_PROBES 2
    opt_set Z_CLEARANCE_MULTI_PROBE 2
    opt_enable Z_MIN_PROBE_REPEATABILITY_TEST
    opt_enable AUTO_BED_LEVELING_BILINEAR
    opt_enable DEBUG_LEVELING_FEATURE
    opt_enable ABL_BILINEAR_SUBDIVISION
    opt_enable LCD_BED_LEVELING
    opt_enable LCD_BED_TRAMMING
    opt_enable Z_SAFE_HOMING
    opt_set Z_SAFE_HOMING_X_POINT X_CENTER
    opt_set Z_SAFE_HOMING_Y_POINT Y_CENTER
    opt_set HOMING_FEEDRATE_MM_M '{ (60*60), (60*60), (12*60) }'
    opt_set PREHEAT_1_TEMP_HOTEND 200
    opt_set PREHEAT_1_TEMP_BED 60
    opt_set PREHEAT_2_TEMP_HOTEND 235
    opt_set PREHEAT_2_TEMP_BED 110
    opt_disable NOZZLE_PARK_FEATURE
    opt_disable DWIN_CREALITY_LCD
    opt_disable DWIN_MARLINUI_LANDSCAPE
    opt_enable DWIN_MARLINUI_PORTRAIT

    opt_enable BABYSTEP_ZPROBE_OFFSET
    opt_enable HOST_ACTION_COMMANDS
    opt_enable HOST_PROMPT_SUPPORT

    MACHINE_UUID="cc4afbb5-716f-4b2b-ad1a-90ba720b1b8a"
elif [ "${ENVIRONMENT}" = "wdi3p" ]; then
    cp \
        "${CONFIG_DIR}/config/examples/Wanhao/Duplicator i3 Plus/Configuration.h" \
        "${MARLIN_DIR}/Marlin/"
    if [ -e "${CONFIG_DIR}/config/examples/Wanhao/Duplicator i3 Plus/Configuration_adv.h" ]; then
        cp \
            "${CONFIG_DIR}/config/examples/Wanhao/Duplicator i3 Plus/Configuration_adv.h" \
            "${MARLIN_DIR}/Marlin/"
    fi

    opt_set STRING_CONFIG_H_AUTHOR '"(rfinnie)"'
    opt_set Z_MIN_ENDSTOP_INVERTING false
    opt_set Z_MIN_PROBE_ENDSTOP_INVERTING false
    opt_set DEFAULT_MAX_FEEDRATE '{ 450, 450, 12, 25 }'
    opt_enable BLTOUCH
    opt_set NOZZLE_TO_PROBE_OFFSET '{ -30, -46, -1.70 }'
    opt_set XY_PROBE_FEEDRATE '(120*60)'
    opt_set Z_PROBE_FEEDRATE_FAST '(12*60)'
    opt_set MULTIPLE_PROBING 2
    opt_set Z_CLEARANCE_DEPLOY_PROBE 5
    opt_set Z_CLEARANCE_BETWEEN_PROBES 2
    opt_set Z_CLEARANCE_MULTI_PROBE 2
    opt_set Z_PROBE_OFFSET_RANGE_MIN -10
    opt_set Z_PROBE_OFFSET_RANGE_MAX 10
    opt_enable Z_MIN_PROBE_REPEATABILITY_TEST
    opt_set Z_MAX_POS 174
    opt_enable AUTO_BED_LEVELING_BILINEAR
    opt_enable EXTRAPOLATE_BEYOND_GRID
    opt_enable ABL_BILINEAR_SUBDIVISION
    opt_enable Z_SAFE_HOMING
    opt_set HOMING_FEEDRATE_MM_M '{ (60*60), (60*60), (12*60) }'
    opt_enable EEPROM_AUTO_INIT
    opt_set PREHEAT_1_TEMP_HOTEND 200
    opt_set PREHEAT_1_TEMP_BED 60
    opt_set PREHEAT_1_FAN_SPEED 255
    opt_set PREHEAT_2_TEMP_HOTEND 235
    opt_set PREHEAT_2_FAN_SPEED 255

    opt_enable BABYSTEPPING
    opt_enable BABYSTEP_ZPROBE_OFFSET
    opt_enable HOST_ACTION_COMMANDS
    opt_enable HOST_PROMPT_SUPPORT

    MACHINE_UUID="c6924ed2-0bc7-4066-9142-31dcfeb17d2e"
fi

env \
    READ_FILE="${MARLIN_DIR}/Marlin/Version.h" \
    WRITE_FILE="${MARLIN_DIR}/Marlin/_Version.h" \
    STRING_DISTRIBUTION_DATE="${NOW}" \
    SHORT_BUILD_VERSION="${NOWSHORT}" \
    DETAILED_BUILD_VERSION="${MARLIN_BRANCH}-${MARLIN_BRANCH_DATE}-g${MARLIN_BRANCH_REV} (config ${CONFIG_BRANCH}-${CONFIG_BRANCH_DATE}-g${CONFIG_BRANCH_REV}) (script ${SCRIPT_BRANCH}-${SCRIPT_BRANCH_DATE}-g${SCRIPT_BRANCH_REV})" \
    SOURCE_CODE_URL="github.com/rfinnie/marlin-personal" \
    DEFAULT_MACHINE_UUID="${MACHINE_UUID}" \
    WEBSITE_URL="finnie.org" \
    "${MARLIN_DIR}/buildroot/bin/generate_version"

platformio run --project-dir "${MARLIN_DIR}" --environment "${ENVIRONMENT}" --target clean
platformio run --project-dir "${MARLIN_DIR}" --environment "${ENVIRONMENT}"

if [ -n "${ARTIFACTS_DIR}" ]; then
    mkdir -p "${ARTIFACTS_DIR}/${ENVIRONMENT}"
    cp \
        "${MARLIN_DIR}/Marlin/_Version.h" \
        "${MARLIN_DIR}/Marlin/Configuration.h" \
        "${MARLIN_DIR}/Marlin/Configuration_adv.h" \
        "${ARTIFACTS_DIR}/${ENVIRONMENT}/"

    diff -u "${CONFIG_DIR}/config/default/Configuration.h" "${MARLIN_DIR}/Marlin/Configuration.h" >"${ARTIFACTS_DIR}/${ENVIRONMENT}/Configuration.h.diff" || true
    diff -u "${CONFIG_DIR}/config/default/Configuration_adv.h" "${MARLIN_DIR}/Marlin/Configuration_adv.h" >"${ARTIFACTS_DIR}/${ENVIRONMENT}/Configuration_adv.h.diff" || true

    for fw in "${MARLIN_DIR}/.pio/build/${ENVIRONMENT}"/*.bin "${MARLIN_DIR}/.pio/build/${ENVIRONMENT}"/*.hex; do
        [ -e "${fw}" ] || continue
        cp "${fw}" "${ARTIFACTS_DIR}/${ENVIRONMENT}/"
    done

    if [ "${ENVIRONMENT}" = "e3v2" ]; then
        cp -a "${CONFIG_DIR}/config/examples/Creality/Ender-3 V2/LCD Files" "${ARTIFACTS_DIR}/${ENVIRONMENT}/"
    fi
fi

if [ -n "${TMPBIN}" ]; then
    rm -rf "${TMPBIN}"
fi
