#!/bin/sh

set -e

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
CONFIG_DIR="${SCRIPT_DIR}/Configurations"
MARLIN_DIR="${SCRIPT_DIR}/Marlin"
ARTIFACTS_DIR="${SCRIPT_DIR}/.artifacts"

# All Marlin Python scripts are python3-compatible, but most have a
# "python" shebang.  For python3-only envs, set up a workaround.
if ! command -v python >/dev/null; then
    TMPBIN="$(mktemp -d)"
    ln -sf "$(command -v python3)" "${TMPBIN}/python"
    export PATH="${TMPBIN}:${PATH}"
fi

ENVIRONMENT="${1}"
[ -n "${ENVIRONMENT}" ]
NOW="$(date '+%Y-%m-%d %H:%M:%S')"
NOWSHORT="$(date -d "${NOW}" '+%Y%m%d-%H%M%S')"

git -C "${MARLIN_DIR}" checkout -- \
    platformio.ini \
    Marlin/Configuration.h \
    Marlin/Configuration_adv.h

CONFIG_BRANCH="$(git -C "${CONFIG_DIR}" rev-parse --abbrev-ref HEAD)"
CONFIG_BRANCH_REV="$(git -C "${CONFIG_DIR}" log --format="%h" -n 1 HEAD)"
CONFIG_BRANCH_DATE="$(git -C "${CONFIG_DIR}" show -s --format=%ci HEAD | perl -ne '/^(\d{4})-(\d{2})-(\d{2})/ && print $1 . $2 . $3')"
CONFIG_BRANCH_ID="${CONFIG_BRANCH}-${CONFIG_BRANCH_DATE}-g${CONFIG_BRANCH_REV}"
[ -z "$(git -C "${CONFIG_DIR}" status --porcelain)" ] || CONFIG_BRANCH_ID="${CONFIG_BRANCH_ID}-dirty"

MARLIN_BRANCH="$(git -C "${MARLIN_DIR}" rev-parse --abbrev-ref HEAD)"
MARLIN_BRANCH_REV="$(git -C "${MARLIN_DIR}" log --format="%h" -n 1 HEAD)"
MARLIN_BRANCH_DATE="$(git -C "${MARLIN_DIR}" show -s --format=%ci HEAD | perl -ne '/^(\d{4})-(\d{2})-(\d{2})/ && print $1 . $2 . $3')"
MARLIN_BRANCH_ID="${MARLIN_BRANCH}-${MARLIN_BRANCH_DATE}-g${MARLIN_BRANCH_REV}"
[ -z "$(git -C "${MARLIN_DIR}" status --porcelain)" ] || MARLIN_BRANCH_ID="${MARLIN_BRANCH_ID}-dirty"

SCRIPT_BRANCH="$(git -C "${SCRIPT_DIR}" rev-parse --abbrev-ref HEAD)"
SCRIPT_BRANCH_REV="$(git -C "${SCRIPT_DIR}" log --format="%h" -n 1 HEAD)"
SCRIPT_BRANCH_DATE="$(git -C "${SCRIPT_DIR}" show -s --format=%ci HEAD | perl -ne '/^(\d{4})-(\d{2})-(\d{2})/ && print $1 . $2 . $3')"
SCRIPT_BRANCH_ID="${SCRIPT_BRANCH}-${SCRIPT_BRANCH_DATE}-g${SCRIPT_BRANCH_REV}"
[ -z "$(git -C "${SCRIPT_DIR}" status --porcelain)" ] || SCRIPT_BRANCH_ID="${SCRIPT_BRANCH_ID}-dirty"

cat <<"EOM" >> "${MARLIN_DIR}/platformio.ini"

[env:e3v2]
extends = env:STM32F103RE_creality
build_flags = ${env:STM32F103RE_creality.build_flags} -DCUSTOM_VERSION_FILE=_Version.h

[env:wdi3p]
extends = env:mega2560
build_flags = ${env:mega2560.build_flags} -DCUSTOM_VERSION_FILE=_Version.h
EOM

cd "${MARLIN_DIR}"
PATH="${PATH}:${MARLIN_DIR}/buildroot/bin"

copy_config() {
    config_dir="$1"
    [ -d "${config_dir}" ]
    for file in Configuration.h Configuration_adv.h; do
        if [ -e "${config_dir}/${file}" ]; then
            cp "${config_dir}/${file}" "${MARLIN_DIR}/Marlin/${file}"
        fi
    done
}

if [ "${ENVIRONMENT}" = "e3v2" ]; then
    copy_config "${CONFIG_DIR}/config/examples/Creality/Ender-3 V2/CrealityV422/MarlinUI"

    opt_set STRING_CONFIG_H_AUTHOR '"(rfinnie)"'
    opt_enable PID_EDIT_MENU
    opt_enable PID_AUTOTUNE_MENU
    # E steps from 93 to 424.9 for Creality Sprite direct drive extruder
    opt_set DEFAULT_AXIS_STEPS_PER_UNIT '{ 80, 80, 400, 424.9 }'
    opt_set DEFAULT_MAX_FEEDRATE '{ 500, 500, 12, 25 }'
    opt_disable PROBE_MANUALLY
    opt_enable BLTOUCH
    opt_set NOZZLE_TO_PROBE_OFFSET '{ -41.00, -9.00, -1.90 }'
    opt_set XY_PROBE_FEEDRATE '(120*60)'
    opt_set Z_PROBE_FEEDRATE_FAST '(12*60)'
    opt_set MULTIPLE_PROBING 2
    opt_set Z_CLEARANCE_DEPLOY_PROBE 5
    opt_set Z_CLEARANCE_BETWEEN_PROBES 2
    opt_set Z_CLEARANCE_MULTI_PROBE 2
    opt_enable Z_MIN_PROBE_REPEATABILITY_TEST
    opt_enable AUTO_BED_LEVELING_BILINEAR
    opt_enable DEBUG_LEVELING_FEATURE
    opt_enable ABL_BILINEAR_SUBDIVISION
    opt_enable LCD_BED_LEVELING
    opt_enable LCD_BED_TRAMMING
    opt_enable Z_SAFE_HOMING
    opt_set Z_SAFE_HOMING_X_POINT X_CENTER
    opt_set Z_SAFE_HOMING_Y_POINT Y_CENTER
    opt_set HOMING_FEEDRATE_MM_M '{ (60*60), (60*60), (12*60) }'
    opt_set PREHEAT_1_TEMP_HOTEND 200
    opt_set PREHEAT_1_TEMP_BED 60
    opt_set PREHEAT_1_FAN_SPEED 64
    opt_set PREHEAT_2_TEMP_HOTEND 235
    opt_set PREHEAT_2_TEMP_BED 110
    opt_set PREHEAT_2_FAN_SPEED 128
    opt_set PREHEAT_3_LABEL '"Load/Unload"'
    opt_set PREHEAT_3_TEMP_HOTEND 200
    opt_set PREHEAT_3_TEMP_BED 0
    opt_set PREHEAT_3_TEMP_CHAMBER 35
    opt_set PREHEAT_3_FAN_SPEED 64
    opt_disable NOZZLE_PARK_FEATURE
    opt_disable DWIN_CREALITY_LCD
    opt_disable DWIN_MARLINUI_PORTRAIT
    opt_enable DWIN_MARLINUI_LANDSCAPE
    opt_set MOTHERBOARD BOARD_CREALITY_V427
    opt_set DEFAULT_Kp  31.92
    opt_set DEFAULT_Ki   3.50
    opt_set DEFAULT_Kd  72.77
    opt_set DEFAULT_bedKp  313.89
    opt_set DEFAULT_bedKi   61.31
    opt_set DEFAULT_bedKd 1071.41
    opt_set Z_MAX_POS 204

    opt_enable BABYSTEP_ZPROBE_OFFSET
    opt_enable HOST_ACTION_COMMANDS
    opt_enable HOST_PROMPT_SUPPORT
    opt_enable PROBE_OFFSET_WIZARD
    opt_enable PROBE_DEPLOY_STOW_MENU
    opt_enable LCD_INFO_MENU
    opt_enable TURBO_BACK_MENU_ITEM
    opt_enable PREHEAT_SHORTCUT_MENU_ITEM
    opt_enable LCD_SHOW_E_TOTAL
    opt_enable SET_PROGRESS_MANUALLY
    opt_enable M73_REPORT
    opt_set X_CURRENT 580
    opt_set Y_CURRENT 580
    opt_set Z_CURRENT 580
    opt_set E0_CURRENT 650
    opt_set LCD_SERIAL_PORT 3

    MACHINE_UUID="cc4afbb5-716f-4b2b-ad1a-90ba720b1b8a"
elif [ "${ENVIRONMENT}" = "wdi3p" ]; then
    copy_config "${CONFIG_DIR}/config/examples/Wanhao/Duplicator i3 Plus"

    opt_set STRING_CONFIG_H_AUTHOR '"(rfinnie)"'
    opt_set Z_MIN_ENDSTOP_HIT_STATE HIGH
    opt_set Z_MIN_PROBE_ENDSTOP_HIT_STATE HIGH
    opt_set DEFAULT_MAX_FEEDRATE '{ 450, 450, 12, 25 }'
    opt_enable BLTOUCH
    opt_set NOZZLE_TO_PROBE_OFFSET '{ -30, -46, -1.70 }'
    opt_set XY_PROBE_FEEDRATE '(120*60)'
    opt_set Z_PROBE_FEEDRATE_FAST '(12*60)'
    opt_set MULTIPLE_PROBING 2
    opt_set Z_CLEARANCE_DEPLOY_PROBE 5
    opt_set Z_CLEARANCE_BETWEEN_PROBES 2
    opt_set Z_CLEARANCE_MULTI_PROBE 2
    opt_set PROBE_OFFSET_ZMIN -10
    opt_set PROBE_OFFSET_ZMAX 10
    opt_enable Z_MIN_PROBE_REPEATABILITY_TEST
    opt_set Z_MAX_POS 174
    opt_enable AUTO_BED_LEVELING_BILINEAR
    opt_enable EXTRAPOLATE_BEYOND_GRID
    opt_enable ABL_BILINEAR_SUBDIVISION
    opt_enable Z_SAFE_HOMING
    opt_set HOMING_FEEDRATE_MM_M '{ (60*60), (60*60), (12*60) }'
    opt_enable EEPROM_AUTO_INIT
    opt_set PREHEAT_1_TEMP_HOTEND 200
    opt_set PREHEAT_1_TEMP_BED 60
    opt_set PREHEAT_1_FAN_SPEED 255
    opt_set PREHEAT_2_TEMP_HOTEND 235
    opt_set PREHEAT_2_FAN_SPEED 255

    opt_enable BABYSTEPPING
    opt_enable BABYSTEP_ZPROBE_OFFSET
    opt_enable HOST_ACTION_COMMANDS
    opt_enable HOST_PROMPT_SUPPORT

    MACHINE_UUID="c6924ed2-0bc7-4066-9142-31dcfeb17d2e"
fi

env \
    READ_FILE="${MARLIN_DIR}/Marlin/Version.h" \
    WRITE_FILE="${MARLIN_DIR}/Marlin/_Version.h" \
    STRING_DISTRIBUTION_DATE="${NOW}" \
    SHORT_BUILD_VERSION="${NOWSHORT}" \
    DETAILED_BUILD_VERSION="${MARLIN_BRANCH_ID} config ${CONFIG_BRANCH_ID} script ${SCRIPT_BRANCH_ID}" \
    SOURCE_CODE_URL="github.com/rfinnie/marlin-personal" \
    DEFAULT_MACHINE_UUID="${MACHINE_UUID}" \
    WEBSITE_URL="finnie.org" \
    "${MARLIN_DIR}/buildroot/bin/generate_version"

platformio run --project-dir "${MARLIN_DIR}" --environment "${ENVIRONMENT}" --target clean
platformio run --project-dir "${MARLIN_DIR}" --environment "${ENVIRONMENT}"

if [ -n "${ARTIFACTS_DIR}" ]; then
    _abd="${ARTIFACTS_DIR}/${ENVIRONMENT}/${NOWSHORT}"
    mkdir -p "${_abd}"
    cp \
        "${MARLIN_DIR}/Marlin/_Version.h" \
        "${MARLIN_DIR}/Marlin/Configuration.h" \
        "${MARLIN_DIR}/Marlin/Configuration_adv.h" \
        "${_abd}/"

    diff -u "${CONFIG_DIR}/config/default/Configuration.h" "${MARLIN_DIR}/Marlin/Configuration.h" >"${_abd}/Configuration.h.diff" || true
    diff -u "${CONFIG_DIR}/config/default/Configuration_adv.h" "${MARLIN_DIR}/Marlin/Configuration_adv.h" >"${_abd}/Configuration_adv.h.diff" || true

    for fw in "${MARLIN_DIR}/.pio/build/${ENVIRONMENT}"/*.bin "${MARLIN_DIR}/.pio/build/${ENVIRONMENT}"/*.hex; do
        [ -e "${fw}" ] || continue
        cp "${fw}" "${_abd}/"
    done

    if [ "${ENVIRONMENT}" = "e3v2" ]; then
        cp -a "${CONFIG_DIR}/config/examples/Creality/Ender-3 V2/LCD Files" "${_abd}/"
    fi
fi

if [ -n "${TMPBIN}" ]; then
    rm -rf "${TMPBIN}"
fi
