# SPDX-PackageName: marlin-personal
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://codeberg.org/rfinnie/marlin-personal
# SPDX-FileComment: Woodpecker CI personal workflow
# SPDX-FileCopyrightText: © 2026 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0
---
when:
  - event: ["push", "pull_request", "manual"]
labels:
  platform: "linux/amd64"
steps:
  - name: "Build"
    image: "debian"
    commands: |
      set -x
      apt update
      apt -y install pipx git curl
      pipx install --global platformio

      git clone --depth=1 --no-tags --branch=bugfix-2.1.x https://github.com/MarlinFirmware/Marlin
      git clone --depth=1 --no-tags --branch=bugfix-2.1.x https://github.com/MarlinFirmware/Configurations

      ret=0
      e3v2_ret=0
      ./build-firmware e3v2 || e3v2_ret=$?
      [ "$e3v2_ret" = 0 ] || ret="$e3v2_ret"
      wdi3p_ret=0
      ./build-firmware wdi3p || wdi3p_ret=$?
      [ "$wdi3p_ret" = 0 ] || ret="$wdi3p_ret"
      {
          echo "### Builds"
          echo ""
          echo "- e3v2 exited $${e3v2_ret}"
          echo "- wdi3p exited $${wdi3p_ret}"
          echo ""
      } >>"$${CI_WORKSPACE}/.ci-pipeline-summary"
      artifact_fn="${CI_REPO_NAME}-${CI_PIPELINE_CREATED}-${CI_WORKFLOW_NAME}-${CI_PIPELINE_NUMBER}.tar.gz"
      mkdir -p .artifacts-dist
      tar zcvf ".artifacts-dist/$${artifact_fn}" -C .artifacts .
      curl --fail-with-body -T ".artifacts-dist/$${artifact_fn}" -H "Authorization: Basic $${ASSETS_AUTH}" "http://artifacts.snowman.lan/$${artifact_fn}"
      {
          echo "### Artifacts"
          echo ""
          echo "- http://artifacts.snowman.lan/$${artifact_fn}"
          echo ""
      } >>"$${CI_WORKSPACE}/.ci-pipeline-summary"
      exit "$ret"
    environment:
      ASSETS_AUTH:
        from_secret: "ASSETS_AUTH"
  - name: "Notify Mastodon if failure"
    when:
      - status: ["failure"]
    image: "woodpeckerci/plugin-mastodon-post"
    settings:
      server_url: "https://m29.us"
      access_token:
        from_secret: "m29_token"
      status: |
        🪿 🪿 🪿 FAILURE: {{ CI_REPO }} 🪿 🪿 🪿
        Workflow: {{ CI_WORKFLOW_NAME }} ({{ CI_PIPELINE_EVENT }} on {{ CI_COMMIT_REF }})

        Pipeline: {{ CI_PIPELINE_URL }}
        Commit: {{ CI_PIPELINE_FORGE_URL }}
  - name: "Pipeline summary"
    image: "debian"
    commands: |
      if [ -e "$${CI_WORKSPACE}/.ci-pipeline-summary" ]; then cat "$${CI_WORKSPACE}/.ci-pipeline-summary"; fi
