name: personal-firmware
on:
  pull_request:
    branches:
    - personal
  push:
    branches:
    - personal
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: MarlinFirmware/Configurations
        ref: bugfix-2.1.x
        path: Configurations
    - uses: actions/checkout@v2
      with:
        repository: MarlinFirmware/Marlin
        ref: bugfix-2.1.x
        path: Marlin
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-platformio-pip
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-platformio
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Build Ender 3 V2 firmware
      run: ./build-firmware e3v2
    - name: Build Wanhao Duplicator i3 Plus firmware
      run: ./build-firmware wdi3p
    - uses: actions/upload-artifact@v2
      with:
        name: marlin-firmware-${{ github.job }}-${{ github.run_number }}-${{ github.run_id }}
        path: .artifacts
